"""Updated Migration

Revision ID: 426a3cae6ed0
Revises: 
Create Date: 2025-04-07 12:38:29.292178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426a3cae6ed0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['dbo.Facilities.FacilityId'], ),
    sa.ForeignKeyConstraint(['state_id'], ['dbo.State.StateId'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cms'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['dbo.Facilities.FacilityId'], ),
    sa.ForeignKeyConstraint(['state_id'], ['dbo.State.StateId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='cms'
    )

    op.create_table('case_manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cmt_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cmt_id'], ['cms.cmt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['cms.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cms'
    )
    op.create_table('cmt_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cmt_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('appointments_scheduled', sa.Integer(), nullable=True),
    sa.Column('appointments_completed', sa.Integer(), nullable=True),
    sa.Column('appointments_missed', sa.Integer(), nullable=True),
    sa.Column('drug_pickups_completed', sa.Integer(), nullable=True),
    sa.Column('drug_pickups_missed', sa.Integer(), nullable=True),
    sa.Column('viral_load_collected', sa.Integer(), nullable=True),
    sa.Column('viral_load_suppressed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cmt_id'], ['cms.cmt.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cms'
    )
    op.create_table('case_manager_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_manager_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('appointments_scheduled', sa.Integer(), nullable=True),
    sa.Column('appointments_completed', sa.Integer(), nullable=True),
    sa.Column('appointments_missed', sa.Integer(), nullable=True),
    sa.Column('drug_pickups_completed', sa.Integer(), nullable=True),
    sa.Column('drug_pickups_missed', sa.Integer(), nullable=True),
    sa.Column('viral_load_collected', sa.Integer(), nullable=True),
    sa.Column('viral_load_suppressed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_manager_id'], ['cms.case_manager.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cms'
    )
    
           
  
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('VLAppointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NextVisitDate', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Surname', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('EstimatedNextAppointmentPharmacy', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('PreviousID', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('PatientHospitalNo', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('PhoneNo', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Ageinmonths', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('MaritalStatus', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('LGA_of_Residence', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Firstname', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('UniqueId', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('CurrentAgeMonths', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('CurrentARTRegimen', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('CurrentARTStatus', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DSDModel', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DoesClientsResideinSameLGAasFacility', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('CurrentRegimenLine', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('TI', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('PBSDateCreated', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('VACauseOfDeath', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DateResultReceivedFacility', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DateTransferedIn', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DSDModelType', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DaysOnART', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('PBS', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Educationallevel', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DaysOfARVRefill', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('State_of_Residence', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('patientId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('CauseOfDeath', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DateOfRecapture', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('CaseManager', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('MatchOutcome', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DateGenerated', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('LastDateOfSampleCollection', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Address', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ARTStartDate', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Recapture', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('RecaptureCount', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('JobStatus', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('LastPickupDateCal', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Ageatstartofart', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('IP', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('IPTScreeningDate', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Pharmacy_LastPickupdate', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('Category',
               existing_type=sa.String(length=50),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('EligibleMonth',
               existing_type=sa.String(length=50),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('EligibilityStatus',
               existing_type=sa.String(length=50),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('NextVLDate',
               existing_type=sa.DateTime(),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('AgeBand',
               existing_type=sa.String(length=50),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('DOB',
               existing_type=sa.DateTime(),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('Outcomes_Date',
               existing_type=sa.DateTime(),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('Outcomes',
               existing_type=sa.String(length=100),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('DateofCurrentViralLoad',
               existing_type=sa.DateTime(),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('CurrentViralLoad',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('CurrentPregnancyStatus',
               existing_type=sa.String(length=50),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('Sex',
               existing_type=sa.String(length=10),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('PepID',
               existing_type=sa.String(length=50),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('FacilityName',
               existing_type=sa.String(length=200),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('DatimCode',
               existing_type=sa.String(length=50),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('LGA',
               existing_type=sa.String(length=100),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('State',
               existing_type=sa.String(length=100),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('pk',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('CaseManagerId')

    with op.batch_alter_table('State', schema=None) as batch_op:
        batch_op.alter_column('StateCode',
               existing_type=sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('StateName',
               existing_type=sa.String(length=100),
               type_=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('LineList', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dsdModelType', sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('educationallevel', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bmi', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('areYouHavingNightSweats', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tbTreatmentStopDate', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('daysOnArt', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bp', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ageatstartofart', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('firstTldPickup', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lastDateOfSampleCollection', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('doYouHaveFever', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('version', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('daysToSchedule', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dateofCurrentTbStatus', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stateOfResidence', sa.VARCHAR(length=90, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('currentArtStatusVisit', sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dateEnrolledIntoOtz', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('alphanumericViralLoadResult', sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('peerToPeerMentoship', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sputumAfb', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otzOutcome', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pbs', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lastHeight', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cd4LfaResult', sa.VARCHAR(length=80, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('jobStatus', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ageinmonths', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('firstname', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('csfForCrAgResult', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('positiveLiving', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('serologyForCrAgResult', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fileGenerationDate', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('isPatientEligibleForIpt', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('chestXrayResult', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nextApByCareCard', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phoneNo', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('patientId', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('previousId', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('currentArtStatusPharmacy', sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lgaOfResidence', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lastWeightDate', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pk', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('appointmentStatus', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('causeOfDeath', sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lastPickupDateCal', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('historyOfContactsWithTbPatients', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('maritalStatus', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vaCauseOfDeath', sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ip', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otzOutcomeDate', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('areYouLosingWeight', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('currentTbStatus', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('leadershipTraining', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('culture', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('viralLoadIndication', sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pharmacyLastPickupdatePreviousQuarter', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('artStatusPreviousQuarter', sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('chestXray', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('currentInhReceived', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('firstInhPickupdate', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('indicationAhd', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pbsDateCreated', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cultureResult', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transitionedAdultClinic', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clinicVisitLastdate', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dateofFirstTldPickup', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otzChampionOreintation', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('currentRegimenLine', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dateResultReceivedFacility', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nextVisitDate', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('geneXpert', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sputumAfbResult', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('treatmentLiteracy', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dsdModel', sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kpType', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('roleOfOtz', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('patientHospitalNo', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('adolescentsParticipation', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otherTestTbLamLfLamEtc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('firstCd4', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nextApByPharmPill', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('surname', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lastInhPickupdate', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('firstCd4Date', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uniqueId', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('geneXpertResult', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dateGenerated', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('iptScreeningDate', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('areYouCoughingCurrently', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lastEmrDate', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('regimenLineAtArtStart', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('regimenAtArtStart', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estimatedNextAppointmentPharmacy', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('currentArtRegimen', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tbTreatmentStartDate', sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lastWeight', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('whostage', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('recaptureCount',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('dateOfRecapture',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('recapture',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('dateTransferedIn',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('ti',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('currentArtStatus',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('outcomesDate',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('outcomes',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('dateofCurrentViralLoad',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('currentViralLoad',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('currentPregnancyStatus',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('daysOfArvRefill',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('pharmacyLastPickupdate',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('artStartDate',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('age_band',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('currentAgeMonths',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('currentAge',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('dob',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('sex',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('facilityName',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('datimCode',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('lga',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('caseManagerId',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('pepId',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('uniquePatientId',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)

    with op.batch_alter_table('Facilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('State', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('LgaId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('Lga',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('StateId',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('FacilityName',
               existing_type=sa.String(length=100),
               type_=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('DatimCode',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)

    with op.batch_alter_table('DrugPickupAppointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Surname', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('EstimatedNextAppointmentPharmacy', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('PreviousID', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('PatientHospitalNo', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('CurrentViralLoad', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('PhoneNo', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Ageinmonths', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('MaritalStatus', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('LGA_of_Residence', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Firstname', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('UniqueId', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('CurrentARTStatus', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DSDModel', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('CurrentARTRegimen', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DoesClientsResideinSameLGAasFacility', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('CurrentRegimenLine', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('TI', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('PBSDateCreated', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('VACauseOfDeath', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DateResultReceivedFacility', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DateTransferedIn', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DSDModelType', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('CurrentPregnancyStatus', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DaysOnART', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('PBS', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Educationallevel', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('State_of_Residence', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('patientId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DOB', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('CauseOfDeath', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DateofCurrentViralLoad', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('CaseManager', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('MatchOutcome', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('DateGenerated', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('LastDateOfSampleCollection', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Address', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ARTStartDate', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('JobStatus', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('LastPickupDateCal', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Ageatstartofart', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('IP', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('IPTScreeningDate', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('AgeBand',
               existing_type=sa.String(length=50),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('DateOfRecapture',
               existing_type=sa.DateTime(),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('Recapture',
               existing_type=sa.Boolean(),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('Outcomes_Date',
               existing_type=sa.DateTime(),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('Outcomes',
               existing_type=sa.String(length=100),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('NextVisitDate',
               existing_type=sa.DateTime(),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('Pharmacy_LastPickupdate',
               existing_type=sa.DateTime(),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('Sex',
               existing_type=sa.String(length=10),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('PepID',
               existing_type=sa.String(length=50),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('FacilityName',
               existing_type=sa.String(length=200),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('DatimCode',
               existing_type=sa.String(length=50),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('LGA',
               existing_type=sa.String(length=100),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('State',
               existing_type=sa.String(length=100),
               type_=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('pk',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('CaseManagerId')

    op.create_table('Dhis',
    sa.Column('organisationunitname', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('dataname', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('StateId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('January', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('February', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('March', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('April', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('May', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('June', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('July', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('August', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Sepember', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('October', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Noveber', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('December', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('LineListJob',
    sa.Column('Pk', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('JobStatus', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('LinkCode', sa.NCHAR(length=12, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('FilePath', sa.NVARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('DownloadCount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('JobStatusChangedAt', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('Email', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('QueryParameter', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('UserId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('JobType', sa.NVARCHAR(length=25, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Pk', name='PK__LineList__321507E782C9236F')
    )
    op.create_table('DrugAppointmentSummary',
    sa.Column('State', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('LGA', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('FacilityName', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('TotalAppt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('KeeptAppt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('missedAppt', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('LineListPreviousQuater',
    sa.Column('IP', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('State', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('LGA', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('DatimCode', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('FacilityName', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PepID', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('UniqueId', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PreviousARTStatus', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True)
    )
    op.create_table('NcdMap',
    sa.Column('State', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Lga', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True)
    )
    op.create_table('Sormas',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('StateId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LgaId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ReportingWeek', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CholeraSC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ChorelaRDT', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ChorelaCultured', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('CholeraCC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('LasaSC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('LassaEC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('LassaCC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MeaslesSC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MeaslesEC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MeaslesCC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('YellowFeverSC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('YellowFeverEC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('YellowFeverCC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MonkeyPoxSC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MonkeyPoxEC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MonkeyPoxCC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('CovidSC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('CovidEC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('CovidCC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MalariaSC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MalariaEC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MalariaCC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('DiphtheriaSC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('DiphtheriaEC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('DiphtheriaCC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('AEFISC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('AEFIEC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('AEFICC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('AFPSC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('AFPEC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('AFPCC', sa.NVARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ReportDate', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['LgaId'], ['Lga.LgaId'], name='FK_Sormas_Lga'),
    sa.ForeignKeyConstraint(['StateId'], ['State.StateId'], name='FK_Sormas_State'),
    sa.PrimaryKeyConstraint('Id', name='PK_Sormas')
    )
    op.create_table('RecencyRaw',
    sa.Column('State', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Lga', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ANC4 / ANC1', sa.NVARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Penta 3 drop out rate', sa.NVARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Exclusively Breastfed', sa.NVARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Screen for TB/ 1000', sa.NVARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True)
    )
    op.create_table('PBSProcessedData',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('StateName', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('LgaName', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('FacilityName', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('DatimCode', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('active_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('captured_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valid_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invalid_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duplicate_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unique_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('match_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('no_match_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('generated_date', sa.DATE(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__PBSProce__3213E83F447576D1')
    )
    op.create_table('Lga',
    sa.Column('LgaId', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('LgaName', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('LgaCode', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('StateId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['StateId'], ['State.StateId'], name='FK_Lga_State'),
    sa.PrimaryKeyConstraint('LgaId', name='PK_Lga')
    )
    op.create_table('MetaLookup',
    sa.Column('State', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('StateNdr', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('StateId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('StateCode', sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Lga', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('LgaNdr', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('LgaId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LgaCode', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True)
    )
    op.create_table('VlAgeSex',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('StateId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LgaId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ReportingWeek', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('AgeDisaggregate', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('TxCurr', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Eligible', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SampleCollect', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Result', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Suppression', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Coverage', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('SuppressionRate', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('LLV', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LLVRate', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Undetectable', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('UndetectableRate', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ReportDate', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['LgaId'], ['Lga.LgaId'], name='FK_VlAgeSex_Lga'),
    sa.ForeignKeyConstraint(['StateId'], ['State.StateId'], name='FK_VlAgeSex_State'),
    sa.PrimaryKeyConstraint('Id', name='PK_VlAgeSex')
    )
    op.create_table('PatientsAppointment',
    sa.Column('UniquePatientId', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PepID', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('State', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('FacilityName', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('CurrentArtStatus', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PharmacyLastPickupdate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('LastDateOfSampleCollection', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Pbs', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PbsDateCreated', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Recapture', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('DateOfRecapture', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('RecaptureCount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Category', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('RecaptureStatus', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('BaseCaptureStatus', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True)
    )
    op.create_table('ExcelData',
    sa.Column('Id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('DiseaseName', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Location', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Year', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Number_of_Cases', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MortalityRate', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('IncidenceRate', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PrevalenceRate', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('RiskFactors', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('TreatmentSuccessRate', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True)
    )
    op.create_table('Retention',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('StateId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('LgaId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ReportingWeek', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TXCURR', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('UniqueFingerprints', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ReportDate', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['LgaId'], ['Lga.LgaId'], name='FK_Retention_Lga'),
    sa.ForeignKeyConstraint(['StateId'], ['State.StateId'], name='FK_Retention_State'),
    sa.PrimaryKeyConstraint('Id', name='PK_Retention')
    )
    op.create_table('Saturation',
    sa.Column('StateId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('State', sa.NVARCHAR(length=25, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Saturation', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Facilities', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_table('__EFMigrationsHistory',
    sa.Column('MigrationId', sa.NVARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('ProductVersion', sa.NVARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('MigrationId', name='PK___EFMigrationsHistory')
    )
    op.create_table('OtherDisease',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('StateId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LgaId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ReportingWeek', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Anc4Anc1', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Penta3DropOutRate', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ExclusivelyBreastfed', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ScreenForTb1000', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('FeverTestedForMalaria', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ActForConfirmedMalaria', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ReportDate', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='PK_OtherDisease')
    )
    op.create_table('Vl',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('StateId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LgaId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ReportingWeek', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('FacilityName', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('FacilityCode', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('TXCurrent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('VLEligible', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('VLtoPCRLab', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('VLenteredEMR', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('VLCoverage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('VLCollectedNoResult', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('VLEligibleNotCollected', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('VLSuppressed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('VLSuppression', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('VLUndetected', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('EligibleForTLD', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ActiveOnTLD', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TLDCoverage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('DateGenerated', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('ReportDate', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['LgaId'], ['Lga.LgaId'], name='FK_Vl_Lga'),
    sa.ForeignKeyConstraint(['StateId'], ['State.StateId'], name='FK_Vl_State'),
    sa.PrimaryKeyConstraint('Id', name='PK_Vl')
    )
    op.drop_table('case_manager_performance', schema='cms')
    op.drop_table('cmt_performance', schema='cms')
    op.drop_table('case_manager', schema='cms')
    op.drop_table('user', schema='cms')
    op.drop_table('cmt', schema='cms')
    # ### end Alembic commands ###
